name: Gatsby Publish
permissions:
  contents: write
on:
  push:
    #    branches:
    # - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: sfesenko/setup-sdkman@v0
        with:
          deps: jbake
      - run: jbake -b
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: output

