name: Gatsby Publish

on:
  push:
    #    branches:
    # - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: sfesenko/setup-sdkman@v0
        with:
          deps: jbake
      - run: jbake -b
